version: "3"
 
services:
 
  nasqar:
    image: aymanm/nasqarall:nasqar
    networks:
      - net
    ports:
      - "80"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 9
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 2s
      resources:
        limits:
          cpus: '4'
          memory: 8G
      labels:
        - "traefik.docker.network=prod_net"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefix:/;" 
        - "traefik.backend.loadbalancer.sticky=true"
  loadbalancer:
    image: traefik
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --web \
      --loglevel=DEBUG
    ports:
      - 80:80
      - 9090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      resources:
        limits:
          cpus: '1'
          memory: 8G
      placement:
         constraints: [node.role == manager]
    networks:
      - net
 
networks:
  net:
