# volcano_module.R
source('./R/Enhancedvolcano.R')

create_volcano_plot <- function(res,
                                lab,
                                x,
                                y,
                                title,
                                subtitle,
                                caption,
                                pCutoff,
                                pCutoffCol,
                                FCcutoff,
                                labSize,
                                cutoffLineType,
                                cutoffLineCol,
                                hline,
                                hlineType,
                                hlineCol,
                                hlineWidth,
                                vline,
                                vlineType,
                                vlineCol,
                                vlineWidth,
                                col,
                                colAlpha,
                                pointSize) {
  EnhancedVolcano(res,
                  lab = lab,
                  x = x,
                  y = y,
                  title = title,
                  subtitle = subtitle,
                  caption = caption,
                  pCutoff = pCutoff,
                  FCcutoff = FCcutoff,
                  labSize = labSize,
                  #cutoffLineType = cutoffLineType,
                  cutoffLineCol = cutoffLineCol,
                  hline = hline,
                  #hlineType = hlineType,
                  hlineCol = hlineCol,
                  hlineWidth = hlineWidth,		
                  vline = vline,
                  #vlineType = vlineType,
                  vlineCol = vlineCol,
                  vlineWidth = vlineWidth,
                  col = col,
                  colAlpha = colAlpha,
                  pointSize = pointSize
  )
}
