# volcano_module.R
source('./R/Enhancedvolcano.R')

create_volcano_plot <- function(res,
                                lab,
                                x,
                                y,
                                title,
                                subtitle,
                                caption,
                                pCutoff,
                                pCutoffCol,
                                FCcutoff,
                                labSize,
                                cutoffLineType,
                                cutoffLineCol,
                                cutoffLineWidth,
                                hline,
                                hlineType,
                                hlineCol,
                                hlineWidth,
                                vline,
                                vlineType,
                                vlineCol,
                                vlineWidth,
                                drawConnectors,
                                col,
                                colAlpha,
                                pointSize) {
  EnhancedVolcano(res,
                  lab = lab,
                  x = x,
                  y = y,
                  title = title,
                  subtitle = subtitle,
                  caption = caption,
                  pCutoff = pCutoff,
                  FCcutoff = FCcutoff,
                  labSize = labSize,
                  #cutoffLineType = cutoffLineType,
                  cutoffLineCol = cutoffLineCol,
                  hline = NULL,
                  # hlineType = hlineType,
                  hlineCol = hlineCol,
                  # hlineWidth = hlineWidth,		
                  vline = NULL,
                  # vlineType = vlineType,
                  vlineCol = vlineCol,
                  # vlineWidth = vlineWidth,
                  drawConnectors = drawConnectors,
                  colCustom = col,
                  colAlpha = colAlpha,
                  pointSize = pointSize
  ) 
}
