channels:
  - conda-forge
  - bioconda
  - anaconda
  - r
  - defaults
dependencies:
  - bcbio-gff
  - bedtools
  - biopython<=1.81
  - pip
  - python>=3.7.6,<=3.11
  - r>=4.3.0
  - r-biocmanager
  - r-caret
  - r-dplyr
  - r-dt
  - r-devtools
  - r-forcats
  - r-ggplot2>=3.4.0
  - r-ggplotify
  - r-gridbase
  - r-gridextra
  - r-htmltools
  - r-jsonlite
  - r-optparse
  - r-plotly
  - r-plyr
  - r-pROC
  - r-purrr
  - r-rmarkdown
  - r-reshape
  - r-readr
  - r-randomForest
  - r-scales
  - r-stringi
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-shiny
  - bioconductor-deseq2
