# volcano_module.R
source('./R/Enhancedvolcano.R')

create_volcano_plot <- function(toptable,
                                lab,
                                x,
                                y,
                                title,
                                subtitle,
                                caption,
                                legendPosition,
                                pCutoff,
                                pCutoffCol,
                                FCcutoff,
                                labSize,
                                cutoffLineType,
                                cutoffLineCol,
                                cutoffLineWidth,
                                hline,
                                hlineType,
                                hlineCol,
                                vline,
								vlineCol,
                                vlineWidth,
                                drawConnectors,
                                colCustom,
                                colAlpha,
                                pointSize) {
  EnhancedVolcano(toptable,
                  lab = lab,
                  x = x,
                  y = y,
                  title = title,
                  subtitle = subtitle,
                  caption = caption,
                  legendPosition = legendPosition,
                  pCutoff = pCutoff,
                  FCcutoff = FCcutoff,
                  labSize = labSize,
                  cutoffLineType = cutoffLineType,
                  cutoffLineCol = cutoffLineCol,
                  hline = NULL,
                  hlineCol = hlineCol,		
                  vline = NULL,
				  vlineCol = vlineCol,
                  drawConnectors = drawConnectors,
                  colCustom = colCustom,
                  colAlpha = colAlpha,
                  pointSize = pointSize
  ) 
}
