library(shiny)
library(shinyjs)
library(dplyr)
library(shinycssloaders)
library(colourpicker)
library(bslib)

# Define UI
ui <- fluidPage(
  titlePanel("Volcano Plot Shiny App"),
  sidebarLayout(
    sidebarPanel(
      evolPlotUI("volcanoPlot") # Call the UI function from e_volcano_plot.R
    ),
    mainPanel(
      plotOutput("volcanoPlot_e_volcano_plot") # Ensure the plot output ID matches the one generated by evolPlotUI
    )
  )
)

# Define server
server <- function(input, output, session) {
  # Example reactive data (replace with actual data or reactive expression as needed)
  data <- reactive({
    # Example dataset, replace with actual data
    df <- data.frame(
      Event = letters[1:10],
      FoldChange = runif(10, -2, 2),
      PValue = runif(10, 0, 0.05),
      Expression = rnorm(10)
    )
    return(df)
  })
  
  # Call the server function from e_volcano_plot.R
  evolPlotServer("volcanoPlot", data, 
                 event_column = reactive("Event"), 
                 fold_change_column = reactive("FoldChange"), 
                 significance_column = reactive("PValue"),
                 significance_threshold = 0.05, 
                 fold_change_threshold = 1)
}

# Run the application 
shinyApp(ui = ui, server = server)

